version: '3.2'
services:
  localstack:
    container_name: localstack-test
    image: localstack/localstack-light:latest
    ports:
      - "4566:4566"
      - "4571:4571"
      - "9000:9000"
    environment:
      - SERVICES=dynamodb,cloudwatch,sqs,s3,ec2
      - DEBUG=1 localstack start
      - DATA_DIR=/tmp/localstack/data
      - PORT_WEB_UI=9000
      - LAMBDA_EXECUTOR=docker
      - DOCKER_HOST=unix:///var/run/docker.sock
      - HOSTNAME_EXTERNAL=localhost
      - START_WEB=1
    # volumes:
    #   - "${TMPDIR:-/tmp/localstack}:/tmp/localstack"
    #   - "/var/run/docker.sock:/var/run/docker.sock"